=== devpassion/weblib/weblib/src/main/resources/forms_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (C) 2011 e-cosystems — Tous droits réservés.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

-->

<xsd:schema xmlns:xsd = "http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.e-cosystems.org/forms"
	xmlns:fs="http://www.e-cosystems.org/forms"
elementFormDefault="qualified" attributeFormDefault="unqualified"  >


<!-- Elements -->

<!-- Attributs -->

<xsd:attribute name="formName" type="xsd:string">
	<xsd:annotation>
		<xsd:documentation>
		Nom du formulaire.
		</xsd:documentation>
	</xsd:annotation>
</xsd:attribute>
<xsd:attribute name="bean" type="xsd:string">
	<xsd:annotation>
		<xsd:documentation>
		Classe du bean de formulaire.	
		</xsd:documentation>
	</xsd:annotation>
</xsd:attribute>
<xsd:attribute name="sessionPersistent" type="xsd:boolean">
	<xsd:annotation>
		<xsd:documentation>
		Indique si le champ est persistant dans la session.
		</xsd:documentation>
	</xsd:annotation>
</xsd:attribute>

<xsd:attribute name="flush" type="xsd:string">
	<xsd:annotation>
		<xsd:documentation>
		Indique les formulaires à vider lors de la validation (liste de noms séparés par des virgules).
		</xsd:documentation>
	</xsd:annotation>
</xsd:attribute>

<xsd:attribute name="validator" type="xsd:string">
	<xsd:annotation>
		<xsd:documentation>
		Validateur de champ.
		</xsd:documentation>
	</xsd:annotation>
</xsd:attribute>
<xsd:attribute name="validatorClass" type="xsd:string">
	<xsd:annotation>
		<xsd:documentation>
		Classe du validateur de champ.
		</xsd:documentation>
	</xsd:annotation>
</xsd:attribute>
<xsd:attribute name="validatorRule" type="xsd:string">
	<xsd:annotation>
		<xsd:documentation>
		Règle de validation.
		</xsd:documentation>
	</xsd:annotation>
</xsd:attribute>


<xsd:attribute name="converter" type="xsd:string">
	<xsd:annotation>
		<xsd:documentation>
		Classe du convertisseur.
		</xsd:documentation>
	</xsd:annotation>
</xsd:attribute>
<xsd:attribute name="name" type="xsd:string">
	<xsd:annotation>
		<xsd:documentation>
		Nom du champ.
		</xsd:documentation>
	</xsd:annotation>
</xsd:attribute>
<xsd:attribute name="required" type="xsd:boolean">
	<xsd:annotation>
		<xsd:documentation>
		Indique si le champ est requis.
		</xsd:documentation>
	</xsd:annotation>
</xsd:attribute>
<xsd:attribute name="listener" type="xsd:string">
	<xsd:annotation>
		<xsd:documentation>
		Ecouteur appelé lors de la validation du formulaire.
		</xsd:documentation>
	</xsd:annotation>
</xsd:attribute>
<xsd:attribute name="validRedirect" type="xsd:anyURI">
	<xsd:annotation>
		<xsd:documentation>
		URL de redirection lorsque le formulaire est valide.
		</xsd:documentation>
	</xsd:annotation>
</xsd:attribute>

<!--Complex Elements-->


<xsd:element name="option">
	<xsd:annotation>
		<xsd:documentation>
			Options de validateur
		</xsd:documentation>
	</xsd:annotation>
	<xsd:complexType>
		<xsd:attribute name="key" use="required" id="key"></xsd:attribute>
		<xsd:attribute name="value" use="required" id="value"></xsd:attribute>		
	</xsd:complexType>
</xsd:element>


<xsd:element name="validator">
	<xsd:annotation>
		<xsd:documentation>
		Validateur de champ
		</xsd:documentation>
	</xsd:annotation>
    <xsd:complexType>
        <xsd:sequence>
        	<xsd:element minOccurs="0" maxOccurs="unbounded" ref="fs:option" ></xsd:element>
        </xsd:sequence>
        <xsd:attribute ref="fs:validatorClass" use="required"></xsd:attribute>
<!--        <xsd:attribute ref="validatorRule" use="required"></xsd:attribute>-->
    </xsd:complexType>
</xsd:element>

<xsd:element name="validators">	
	<xsd:annotation>
		<xsd:documentation>
		Validateurs de champ.
		</xsd:documentation>
	</xsd:annotation>
    <xsd:complexType>
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" ref="fs:validator"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:element>

<xsd:element name="field">
	<xsd:annotation>
		<xsd:documentation>
		Champ de formulaire.
		</xsd:documentation>
	</xsd:annotation>
    <xsd:complexType>
        <xsd:sequence>
            <xsd:element minOccurs="0" maxOccurs="1" ref="fs:validators" ></xsd:element>
        </xsd:sequence>
        <xsd:attribute ref="fs:validator" use="prohibited" ></xsd:attribute>
        <xsd:attribute ref="fs:converter" use="required" ></xsd:attribute>
        <xsd:attribute ref="fs:name" use="required"></xsd:attribute>
        <xsd:attribute ref="fs:required" use="optional" default="false"></xsd:attribute>

    </xsd:complexType>
</xsd:element>

<xsd:element  name="form">
	<xsd:annotation>
		<xsd:documentation>
		Formulaire.
		</xsd:documentation>
	</xsd:annotation>
<xsd:complexType >
    <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="fs:field"></xsd:element>
    </xsd:sequence>
    <xsd:attribute ref="fs:bean" use="required"  ></xsd:attribute>
    <xsd:attribute ref="fs:formName" use="required" ></xsd:attribute>
    <xsd:attribute ref="fs:listener" use="required" ></xsd:attribute>
    <xsd:attribute ref="fs:sessionPersistent" use="optional" default="false" ></xsd:attribute>
    <xsd:attribute ref="fs:validRedirect" use="optional" default=""></xsd:attribute>
    <xsd:attribute ref="fs:flush" use="optional"></xsd:attribute>
</xsd:complexType>
</xsd:element>


<xsd:element  name="forms" >
	<xsd:annotation>
		<xsd:documentation>
		Liste des formulaires d'une application web.
		</xsd:documentation>
	</xsd:annotation>
<xsd:complexType>
    <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="fs:form"></xsd:element>
    </xsd:sequence>
    </xsd:complexType>
</xsd:element>

 </xsd:schema>

=== devpassion/weblib/weblib/src/test/resources/testForm.xml
<?xml version="1.0" encoding="UTF-8"?>
<fs:forms 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.e-cosystems.org/forms ../../main/resources/forms_schema.xsd"
	xmlns:fs="http://www.e-cosystems.org/forms"
	xmlns="http://www.e-cosystems.org/forms"
	>
	
  <fs:form fs:formName="party" fs:bean="org.ecosystems.weblib.html.form.Party" fs:listener="org.ecosystems.weblib.html.form.PartyListener" fs:sessionPersistent="true" >
        <fs:field fs:name="title"
                fs:converter="org.ecosystems.weblib.html.form.StringConverter" fs:required="true" >
            <fs:validators>
                <fs:validator fs:validatorClass="org.ecosystems.weblib.html.form.NotNullValidator" />
            </fs:validators>
        </fs:field>

        <fs:field fs:name="address"
            fs:converter="org.ecosystems.weblib.html.form.StringConverter" fs:required="true" >
                <fs:validators>
                    <fs:validator fs:validatorClass="org.ecosystems.weblib.html.form.NotNullValidator" />
                </fs:validators>
            </fs:field>

        <fs:field fs:name="date" fs:converter="org.ecosystems.weblib.html.form.DateConverter" fs:required="true" >

            <fs:validators>
                <fs:validator fs:validatorClass="org.ecosystems.weblib.html.form.NotNullValidator"/>
                <fs:validator fs:validatorClass="org.ecosystems.weblib.html.form.DateValidator" />
            </fs:validators>

        </fs:field>

        <fs:field fs:name="lat" fs:converter="org.ecosystems.weblib.html.form.NumericConverter" fs:required="true" >
            <fs:validators>
                <fs:validator fs:validatorClass="org.ecosystems.weblib.html.form.NotNullValidator"/>
                <fs:validator fs:validatorClass="org.ecosystems.weblib.html.form.NumericValidator"/>
            </fs:validators>
        </fs:field>

        <fs:field fs:name="lng" fs:converter="org.ecosystems.weblib.html.form.NumericConverter" fs:required="true" >
            <fs:validators>
                <fs:validator fs:validatorClass="org.ecosystems.weblib.html.form.NotNullValidator"/>
                <fs:validator fs:validatorClass="org.ecosystems.weblib.html.form.NumericValidator"/>
            </fs:validators>
        </fs:field>




        <fs:field fs:name="time" fs:converter="org.ecosystems.weblib.html.form.TimeConverter">
            <fs:validators>
                <fs:validator fs:validatorClass="org.ecosystems.weblib.html.form.TimeValidator"/>
            </fs:validators>
        </fs:field>

        <fs:field fs:name="name" fs:converter="org.ecosystems.weblib.html.form.StringConverter" fs:required="true" >
            <fs:validators>
                <fs:validator fs:validatorClass="org.ecosystems.weblib.html.form.NotNullValidator"/>
            </fs:validators>
        </fs:field>

        <fs:field fs:name="description"
            fs:converter="org.ecosystems.weblib.html.form.StringConverter" fs:required="false" >
        </fs:field>

        <fs:field fs:name="mail" fs:converter="org.ecosystems.weblib.html.form.StringConverter" fs:required="true" >
            <fs:validators>
                <fs:validator fs:validatorClass="org.ecosystems.weblib.html.form.NotNullValidator"/>
                <fs:validator fs:validatorClass="org.ecosystems.weblib.html.form.MailValidator"/>
            </fs:validators>
        </fs:field>
	
		<fs:field fs:name="lang" fs:converter="org.ecosystems.weblib.html.form.StringConverter" fs:required="true" >
            <fs:validators>
                <fs:validator fs:validatorClass="org.ecosystems.weblib.html.form.LangCodeValidator"/>
            </fs:validators>
        </fs:field>

    </fs:form>

</fs:forms>

=== devpassion/weblib/weblibtests/src/main/webapp/WEB-INF/testForm.xml
<?xml version="1.0" encoding="UTF-8"?>
<fs:forms 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.e-cosystems.org/forms jar:file//home/tim288/.m2/repository/org/ecosystems/weblib/0.0.2/weblib-0.0.2.jar!/forms_schema.xsd"
	xmlns:fs="http://www.e-cosystems.org/forms"
	xmlns="http://www.e-cosystems.org/forms"
	>
	
  <fs:form fs:formName="party" fs:bean="org.ecosystems.weblibtests.model.Party" fs:listener="org.ecosystems.weblibtests.control.PartyListener" fs:sessionPersistent="true" >
        <fs:field fs:name="title"
                fs:converter="org.ecosystems.weblib.html.form.StringConverter" fs:required="true" >
            <fs:validators>
                <fs:validator fs:validatorClass="org.ecosystems.weblib.html.form.NotNullValidator" />
            </fs:validators>
        </fs:field>

        <fs:field fs:name="address"
            fs:converter="org.ecosystems.weblib.html.form.StringConverter" fs:required="true" >
                <fs:validators>
                    <fs:validator fs:validatorClass="org.ecosystems.weblib.html.form.NotNullValidator" />
                </fs:validators>
            </fs:field>

        <fs:field fs:name="date" fs:converter="org.ecosystems.weblib.html.form.DateConverter" fs:required="true" >

            <fs:validators>
                <fs:validator fs:validatorClass="org.ecosystems.weblib.html.form.NotNullValidator"/>
                <fs:validator fs:validatorClass="org.ecosystems.weblib.html.form.DateValidator" />
            </fs:validators>

        </fs:field>






        <fs:field fs:name="time" fs:converter="org.ecosystems.weblib.html.form.TimeConverter">
            <fs:validators>
                <fs:validator fs:validatorClass="org.ecosystems.weblib.html.form.TimeValidator"/>
            </fs:validators>
        </fs:field>

        <fs:field fs:name="name" fs:converter="org.ecosystems.weblib.html.form.StringConverter" fs:required="true" >
            <fs:validators>
                <fs:validator fs:validatorClass="org.ecosystems.weblib.html.form.NotNullValidator"/>
            </fs:validators>
        </fs:field>

        <fs:field fs:name="description"
            fs:converter="org.ecosystems.weblib.html.form.StringConverter" fs:required="false" >
        </fs:field>

        <fs:field fs:name="mail" fs:converter="org.ecosystems.weblib.html.form.StringConverter" fs:required="true" >
            <fs:validators>
                <fs:validator fs:validatorClass="org.ecosystems.weblib.html.form.NotNullValidator"/>
                <fs:validator fs:validatorClass="org.ecosystems.weblib.html.form.MailValidator"/>
            </fs:validators>
        </fs:field>
		
		<fs:field fs:name="image" fs:converter="org.ecosystems.weblib.html.form.FileConverter" fs:required="false" >
            <fs:validators>
                 <fs:validator fs:validatorClass="org.ecosystems.weblib.html.form.ImageFileValidator"/>
                 <fs:validator fs:validatorClass="org.ecosystems.weblib.html.form.NotNullValidator"/>
            </fs:validators>
        </fs:field>
		
		
		
    </fs:form>


	
	
	
	<form fs:bean="org.ecosystems.weblibtests.model.Logo" fs:formName="add" fs:listener="org.ecosystems.weblibtests.servlet.AddFormListener" fs:validRedirect="/added.html">
		
		<field fs:required="true" fs:name="name" fs:converter="org.ecosystems.weblib.html.form.StringConverter">
			<validators>
                <validator fs:validatorClass="org.ecosystems.weblib.html.form.NotNullValidator" />
                <validator fs:validatorClass="org.ecosystems.weblib.html.form.HTMLStringValidator" />
            </validators>
		</field>
		
		
		<field fs:required="true" fs:name="image" fs:converter="org.ecosystems.weblib.html.form.FileConverter">
			<validators>
                <validator fs:validatorClass="org.ecosystems.weblib.html.form.NotNullValidator" />
                <validator fs:validatorClass="org.ecosystems.weblib.html.form.ImageFileValidator" />
                
            </validators>
		</field>
		
		<field fs:required="true" fs:name="comments" fs:converter="org.ecosystems.weblib.html.form.StringConverter">
			<validators>
                <validator fs:validatorClass="org.ecosystems.weblib.html.form.NotNullValidator" />
                <validator fs:validatorClass="org.ecosystems.weblib.html.form.HTMLStringValidator" />
            </validators>
		</field>
		
		<field fs:name="link" fs:converter="org.ecosystems.weblib.html.form.StringConverter">
			<validators>
                <validator fs:validatorClass="org.ecosystems.weblib.html.form.NotNullValidator" />
                <validator fs:validatorClass="org.ecosystems.weblib.html.form.HTMLStringValidator" />
            </validators>
		</field>
		
		<field fs:name="linkInfo" fs:converter="org.ecosystems.weblib.html.form.StringConverter">
			<validators>
                <validator fs:validatorClass="org.ecosystems.weblib.html.form.NotNullValidator" />
                <validator fs:validatorClass="org.ecosystems.weblib.html.form.HTMLStringValidator" />
            </validators>
		</field>
		
		
		
		
		
		
		<field fs:name="lang" fs:converter="org.ecosystems.weblib.html.form.StringConverter">
			<validators>
                <validator fs:validatorClass="org.ecosystems.weblib.html.form.NotNullValidator" />
                <validator fs:validatorClass="org.ecosystems.weblib.html.form.LangCodeValidator" />                
            </validators>
		</field>
		
		<field fs:name="category" fs:converter="org.ecosystems.weblibtests.control.CategorieSetConverter">
			<validators>
                <validator fs:validatorClass="org.ecosystems.weblib.html.form.NotNullValidator" />
                <validator fs:validatorClass="org.ecosystems.weblib.html.form.FilledSetValidator" />
                
                <validator fs:validatorClass="org.ecosystems.weblibtests.control.CategorieArrayValidator" />                
            </validators>
		</field>
		
		
		
		
		</form>
	
	
	

</fs:forms>
